# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9d1a91d6c4ac5552ef64f8864d00da76001ee2450d9fe53ea3c5d72f2489b9d1d1f3bf9cda98b460c5e11018f938631e2430a4b4d359378f87e6c68fff5567

test:
  secret_key_base: 36e7c42d26bae854629d61aa18a6c2c796c22eb6f9a7256c44e5d4d401cde56de312e0e743a4cdc580b6a17adae34412b67ae10a641fba3d1d2475d73dee034d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
